### ISSUE TITLE
Lid closing is not detected

### ISSUE THREAD

**Issue by minhduc0711** [alex-courtis/way-displays#15]
When I close my laptop lid, the workspaces on the laptop monitor are not moved to the external monitor at all. The message `Lid closed` does not show up in the logs either.

However, `cat /proc/acpi/button/lid/LID0/state` still outputs the correct state of my lid.

Additional info:
* sway version 1.6-f2b6d1ec 
* wlroots 07ccc6e0
* way-displays 1.2.1

**Comment by alex-courtis** [comment]
Are you seeing a `Monitoring lid device: /dev/input/eventX` message as per [example session](https://github.com/alex-courtis/way-displays/blob/master/doc/example-session.md#starting-up)? If not, we can add some debug to the lid detection code for you to try.

FYI way-displays is using libinput rather than /proc/acpi to detect the lid. `libinput list-devices` will enumerate them all. `Sleep Button` is the one we are interested in, and the one that we want for `Monitoring lid device: /dev/input/eventX`

**Comment by minhduc0711** [comment]
Sorry, I overlooked the warning message that complains about permission to `/dev/input/event0`. It works properly after I add myself to the `input` group.

**Comment by alex-courtis** [comment]
Good to hear it is working.

Could you please post that warning message? I will add it to a troubleshooting section of the README

**Comment by minhduc0711** [comment]
Yes, here it is:
```
W [10:09:44.542] WARNING: open '/dev/input/event0' failed 13: 'Permission denied'
```

**Comment by alex-courtis** [comment]
Thank you. Added to the [README](https://github.com/alex-courtis/way-displays/blob/master/README.md#known-issues)

**Comment by simoneruffini** [comment]
> Thank you. Added to the [README](https://github.com/alex-courtis/way-displays/blob/master/README.md#known-issues)

I think this should be publicized better! Not as a common issue/workaround  but as an installation constraint. Moreover the solution is not even simple to find it in the README.md (via a web browser from the github page) because the content written in the `<details>` section is hidden even to a find in page action (Ctrl+f). I would suggest to remove the details sections in the readme file.

**Comment by alex-courtis** [comment]
> as an installation constraint.

Yes. That is sensible.

> I would suggest to remove the `<details>` tags in the readme file.

Those collapsed sections are a problem. I'll think about a better layout e.g. split into multiple files.

**Comment by alex-courtis** [comment]
work in progress... looks like it's time for a wiki
