### ISSUE TITLE
Question: Mix row and columns?

### ISSUE THREAD

**Issue by mwaltersva** [alex-courtis/way-displays#158]
Sorry if this has been asked an answered, I couldn't find it. I have two external monitors arranged side by side, with my laptop below the rightmost monitor. Is it possible to represent this in way-displays? I couldn't see a way specify the alignment of a single display in the documentation. Thank you!

Edit: alternatively, can I specify an absolute position for a monitor like with the swaymsg output settings.

**Comment by alex-courtis** [comment]
That is indeed a desirable feature however it's not a trivial task due to variable scales and thus sizes. See #79

If you don't need any dynamic scaling you can use https://sr.ht/~emersion/kanshi/ or direct `man 5 sway-output` commands to hardcode sizes and positions.

I'll close this issue; let's continue to discuss in #79

**Comment by alex-courtis** [comment]
Any ideas, insights, thoughts would be most gratefully appreciated!

This one's not technically difficult, but difficult from the perspective of configration and definition of the positions.
